#spring:
#  config:
#    activate:
#      on-profile: "prod"
#
#build:
#  version: "2.0"
#
#cards:
#  message: "Welcome to EasyBank cards related prod APIs"
#  contactDetails:
#    name" : "Bao Nguyen - Product Owner"
#    email: "nguyenducbaokey@gmail.com"
#  onCallSupport:
#    - (+84) 788 049 042
#    - (+84) 123 456 789
